export const REST_PATHS = {
  marketStats: '/stats/market',
  platformFee: '/config/platform-fee',
  tasks: '/tasks',
  tasksMine: '/tasks/mine',
  task: (id: number | string) => `/tasks/${id}`,
  taskApplications: (id: number | string) => `/tasks/${id}/applications`,
  taskProposals: (id: number | string) => `/tasks/${id}/proposals`,
  taskSelectProposal: (taskId: number | string, proposalId: number | string) =>
    `/tasks/${taskId}/proposals/${proposalId}/select`,
  taskCancel: (id: number | string) => `/tasks/${id}/cancel`,
  privateOffers: '/private-offers',
  taskPrivateFinalize: (id: number | string) => `/tasks/${id}/private/finalize`,
  taskPrivateAccept: (id: number | string) => `/tasks/${id}/private/accept`,
  taskPrivateReject: (id: number | string) => `/tasks/${id}/private/reject`,
  deals: '/deals',
  deal: (id: string) => `/deals/${id}`,
  dealToken: (token: string) => `/deals/token/${token}`,
  dealAccept: (id: string) => `/deals/${id}/accept`,
  dealComplete: (id: string) => `/deals/${id}/complete`,
  taskEscrow: (id: number | string) => `/tasks/${id}/escrow`,
  taskEscrowWorkStarted: (id: number | string) => `/tasks/${id}/escrow/work-started`,
  taskEscrowReleaseConfirm: (id: number | string) => `/tasks/${id}/escrow/release/confirm`,
  dealEscrowPrepare: (id: string) => `/deals/${id}/escrow/prepare`,
  dealEscrowFinalize: (id: string) => `/deals/${id}/escrow/finalize`,
  dealEscrowReleaseConfirm: (id: string) => `/deals/${id}/escrow/release/confirm`,
  escrowQuote: '/escrow/quote',
  disputes: '/disputes',
  disputesResolved: '/disputes/resolved',
  disputeChat: (id: number | string) => `/disputes/${id}/chat`,
  disputeFiles: (id: number | string) => `/disputes/${id}/files`,
  disputeTimeline: (id: number | string) => `/disputes/${id}/timeline`,
  taskDisputeChat: (taskId: number | string) => `/tasks/${taskId}/disputes/chat`,
  taskDisputeFiles: (taskId: number | string) => `/tasks/${taskId}/disputes/files`,
  taskDisputeTimeline: (taskId: number | string) => `/tasks/${taskId}/disputes/timeline`,
  dealDisputeChat: (dealId: string) => `/deals/${dealId}/disputes/chat`,
  dealDisputeFiles: (dealId: string) => `/deals/${dealId}/disputes/files`,
  dealDisputeTimeline: (dealId: string) => `/deals/${dealId}/disputes/timeline`,
  taskEvidence: (taskId: number | string) => `/tasks/${taskId}/evidence`,
  dealEvidence: (dealId: string) => `/deals/${dealId}/evidence`,
  ratings: '/ratings',
  userRatingSummary: (userId: number | string) => `/users/${userId}/ratings/summary`,
  walletRegister: '/wallets/register',
  walletVerify: '/wallets/verify',
  escrowDeployPrepare: (taskId: number | string) => `/tasks/${taskId}/escrow/deploy/prepare`,
  escrowDeployConfirm: (taskId: number | string) => `/tasks/${taskId}/escrow/deploy/confirm`,
  escrowFundPrepare: (taskId: number | string) => `/tasks/${taskId}/escrow/fund/prepare`,
  escrowFundConfirm: (taskId: number | string) => `/tasks/${taskId}/escrow/fund/confirm`,
  escrowReleasePrepare: (taskId: number | string) => `/tasks/${taskId}/escrow/release/prepare`,
  escrowReleaseConfirm: (taskId: number | string) => `/tasks/${taskId}/escrow/release/confirm`,
  webhookDeliveries: '/webhooks/deliveries',
  taskEvidenceUpload: (taskId: number | string) => `/tasks/${taskId}/evidence`,
  dealEvidenceUpload: (dealId: string) => `/deals/${dealId}/evidence`,
  jobs: '/jobs',
  job: (id: string) => `/jobs/${id}`,
  jobCancel: (id: string) => `/jobs/${id}/cancel`,
  jobSubjobs: (jobId: string) => `/jobs/${jobId}/subjobs`,
  subjobsMine: '/subjobs/mine',
  subjob: (id: string) => `/subjobs/${id}`,
  subjobEscrowQuote: (id: string) => `/subjobs/${id}/escrow/quote`,
  subjobEscrowDeployPrepare: (id: string) => `/subjobs/${id}/escrow/deploy/prepare`,
  subjobEscrowDeployConfirm: (id: string) => `/subjobs/${id}/escrow/deploy/confirm`,
  subjobEscrowFundPrepare: (id: string) => `/subjobs/${id}/escrow/fund/prepare`,
  subjobEscrowFundConfirm: (id: string) => `/subjobs/${id}/escrow/fund/confirm`,
  subjobEscrowReleasePrepare: (id: string) => `/subjobs/${id}/escrow/release/prepare`,
  subjobEscrowReleaseConfirm: (id: string) => `/subjobs/${id}/escrow/release/confirm`,
  subjobAttest: (id: string) => `/subjobs/${id}/attest`,
  subjobWorkStarted: (id: string) => `/subjobs/${id}/work-started`,
  subjobCancel: (id: string) => `/subjobs/${id}/cancel`,
  subjobLinkProposal: (id: string) => `/subjobs/${id}/link-proposal`,
  subjobReleaseOnCallback: (id: string) => `/subjobs/${id}/release-on-callback`,
  configApiKeys: '/config/api-keys',
  configApiKeysContext: '/config/api-keys/context',
  configApiKeysRevoke: '/config/api-keys/revoke',
} as const;

export const LEGACY_ACTIONS = {
  getMarketStats: 'get_landing_market_stats',
  getPlatformFee: 'get_platform_fee',
  getTasks: 'get_tasks',
  createTask: 'create_task',
  getTaskDetails: 'get_task_details',
  getUserTasks: 'get_user_tasks',
  applyTask: 'apply_task',
  getTaskProposals: 'get_task_proposals',
  selectProposal: 'select_proposal',
  cancelTask: 'cancel_task',
  getPrivateOffers: 'get_private_offers',
  finalizePrivateOffer: 'finalize_private_offer',
  acceptPrivateOffer: 'accept_private_offer',
  rejectPrivateOffer: 'reject_private_offer',
  createDeal: 'create_deal',
  getDealByToken: 'get_deal_by_token',
  getDealDetails: 'get_deal_details',
  getMyDeals: 'get_my_deals',
  acceptDeal: 'accept_deal',
  completeDeal: 'complete_deal',
  createEscrow: 'create_escrow',
  getEscrowStatus: 'get_escrow_status',
  markWorkStarted: 'mark_work_started',
  prepareDealEscrow: 'prepare_deal_escrow',
  finalizeDealEscrow: 'finalize_deal_escrow',
  completeTask: 'complete_task',
  markDealReleased: 'mark_deal_released',
  getEscrowQuote: 'get_escrow_quote',
  listDisputes: 'list_disputes',
  getUserDisputes: 'get_user_disputes',
  createDispute: 'create_dispute',
  getDisputeChat: 'get_dispute_chat',
  getDisputeFiles: 'get_dispute_files',
  getDisputeTimeline: 'get_dispute_timeline',
  getMilestoneEvidence: 'get_milestone_evidence',
  getDealEvidence: 'get_deal_evidence',
  createRating: 'create_rating',
  getUserRatingSummary: 'get_user_rating_summary',
  registerWallet: 'register_wallet',
  verifyWallet: 'verify_wallet',
  prepareEscrowDeploy: 'prepare_escrow_deploy',
  confirmEscrowDeploy: 'confirm_escrow_deploy',
  prepareEscrowFund: 'prepare_escrow_fund',
  confirmEscrowFund: 'confirm_escrow_fund',
  prepareEscrowRelease: 'prepare_escrow_release',
  confirmEscrowRelease: 'confirm_escrow_release',
  listWebhookDeliveries: 'list_webhook_deliveries',
  uploadMilestoneEvidence: 'upload_milestone_evidence',
  uploadDealEvidence: 'upload_deal_evidence',
  createJob: 'create_job',
  getJob: 'get_job',
  listJobs: 'list_jobs',
  createSubjob: 'create_subjob',
  getSubjob: 'get_subjob',
  subjobEscrowQuote: 'subjob_escrow_quote',
  subjobEscrowDeployPrepare: 'subjob_escrow_deploy_prepare',
  subjobEscrowDeployConfirm: 'subjob_escrow_deploy_confirm',
  subjobEscrowFundPrepare: 'subjob_escrow_fund_prepare',
  subjobEscrowFundConfirm: 'subjob_escrow_fund_confirm',
  subjobEscrowReleasePrepare: 'subjob_escrow_release_prepare',
  subjobEscrowReleaseConfirm: 'subjob_escrow_release_confirm',
  attestSubjob: 'attest_subjob',
  releaseSubjobOnCallback: 'release_subjob_on_callback',
  listSubjobsMine: 'list_subjobs_mine',
  subjobMarkWorkStarted: 'subjob_mark_work_started',
  cancelSubjob: 'cancel_subjob',
  cancelJob: 'cancel_job',
  linkSubjobProposal: 'link_subjob_proposal',
} as const;
