-- Portfolio items (migrado desde MySQL user_portfolio)

CREATE TABLE IF NOT EXISTS public.arcusx_user_portfolio (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.arcusx_users (id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  image_url text,
  project_url text,
  category varchar(50),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_arcusx_user_portfolio_user ON public.arcusx_user_portfolio (user_id);

ALTER TABLE public.arcusx_user_portfolio ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.arcusx_user_portfolio FROM PUBLIC;
GRANT ALL ON TABLE public.arcusx_user_portfolio TO postgres, service_role;
