-- ArcusX core schema (MySQL arcusxon_users → PostgreSQL).
-- Access: RLS enabled, no direct anon/authenticated table access; service_role + SECURITY DEFINER RPCs / Edge Functions.

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.arcusx_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  email text NOT NULL,
  avatar_url text,
  bio text,
  portfolio_url text,
  verified boolean NOT NULL DEFAULT false,
  public_profile boolean NOT NULL DEFAULT true,
  created_at_profile timestamptz,
  role text NOT NULL DEFAULT 'user',
  is_admin boolean NOT NULL DEFAULT false,
  password_hash text NOT NULL DEFAULT '',
  wallet_address text,
  human_id_verified boolean NOT NULL DEFAULT false,
  human_id_hash text,
  human_id_verified_at timestamptz,
  human_id_action_id text,
  supabase_user_id uuid,
  completed_tasks_count integer NOT NULL DEFAULT 0,
  tasks_today integer NOT NULL DEFAULT 0,
  tasks_this_week integer NOT NULL DEFAULT 0,
  last_task_created timestamptz,
  cooldown_until timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  average_rating numeric(3, 2) NOT NULL DEFAULT 0,
  total_ratings integer NOT NULL DEFAULT 0,
  skills jsonb,
  CONSTRAINT arcusx_users_email_unique UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_arcusx_users_supabase_user_id ON public.arcusx_users (supabase_user_id);
CREATE INDEX IF NOT EXISTS idx_arcusx_users_wallet ON public.arcusx_users (wallet_address);
CREATE INDEX IF NOT EXISTS idx_arcusx_users_role ON public.arcusx_users (role);

-- ---------------------------------------------------------------------------
-- Tasks
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.arcusx_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  subtitle text,
  description text NOT NULL,
  price numeric(18, 8) NOT NULL,
  currency text NOT NULL DEFAULT 'USDC',
  difficulty text NOT NULL,
  category text NOT NULL,
  user_id bigint NOT NULL REFERENCES public.arcusx_users (id) ON DELETE CASCADE,
  accepted_applicant_id bigint REFERENCES public.arcusx_users (id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'open',
  client_accepted_completion boolean NOT NULL DEFAULT false,
  worker_accepted_completion boolean NOT NULL DEFAULT false,
  files jsonb,
  escrow_id text,
  escrow_platform_fee numeric(10, 7),
  escrow_trustline_address text,
  escrow_amount numeric(18, 8),
  contract_id text,
  soroban_escrow_id bigint,
  escrow_secret text,
  pending_transaction_xdr text,
  pending_transaction_signer text,
  escrow_status text,
  escrow_created_at timestamptz,
  escrow_completed_at timestamptz,
  scheduled_deletion_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  worker_started_at timestamptz,
  cancellation_requested_at timestamptz,
  cancellation_reason text,
  cancellation_allowed boolean NOT NULL DEFAULT true,
  cancellation_initiated_by bigint REFERENCES public.arcusx_users (id) ON DELETE SET NULL,
  cancellation_tx_hash text
);

CREATE INDEX IF NOT EXISTS idx_arcusx_tasks_user_id ON public.arcusx_tasks (user_id);
CREATE INDEX IF NOT EXISTS idx_arcusx_tasks_status ON public.arcusx_tasks (status);
CREATE INDEX IF NOT EXISTS idx_arcusx_tasks_escrow_status ON public.arcusx_tasks (escrow_status);
CREATE INDEX IF NOT EXISTS idx_arcusx_tasks_created_at ON public.arcusx_tasks (created_at DESC);

-- ---------------------------------------------------------------------------
-- Applications (proposals)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.arcusx_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES public.arcusx_tasks (id) ON DELETE CASCADE,
  applicant_id bigint NOT NULL REFERENCES public.arcusx_users (id) ON DELETE CASCADE,
  message text NOT NULL,
  portfolio_url text,
  worker_wallet_address text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT arcusx_applications_task_applicant_unique UNIQUE (task_id, applicant_id)
);

CREATE INDEX IF NOT EXISTS idx_arcusx_applications_task ON public.arcusx_applications (task_id);
CREATE INDEX IF NOT EXISTS idx_arcusx_applications_applicant ON public.arcusx_applications (applicant_id);

-- ---------------------------------------------------------------------------
-- Disputes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.arcusx_disputes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES public.arcusx_tasks (id) ON DELETE CASCADE,
  created_by bigint NOT NULL REFERENCES public.arcusx_users (id) ON DELETE CASCADE,
  reason text NOT NULL,
  tx_hash text,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'resolved', 'cancelled')),
  resolution text,
  resolved_by bigint REFERENCES public.arcusx_users (id) ON DELETE SET NULL,
  resolved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_arcusx_disputes_task ON public.arcusx_disputes (task_id);
CREATE INDEX IF NOT EXISTS idx_arcusx_disputes_status ON public.arcusx_disputes (status);

-- ---------------------------------------------------------------------------
-- Ratings
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.arcusx_ratings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES public.arcusx_tasks (id),
  rater_id bigint NOT NULL REFERENCES public.arcusx_users (id),
  rated_id bigint NOT NULL REFERENCES public.arcusx_users (id),
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT arcusx_ratings_unique UNIQUE (task_id, rater_id, rated_id)
);

-- ---------------------------------------------------------------------------
-- System config
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.arcusx_system_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_key text NOT NULL UNIQUE,
  config_value text NOT NULL,
  config_type text NOT NULL DEFAULT 'string',
  description text,
  updated_by bigint REFERENCES public.arcusx_users (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Admin logs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.arcusx_admin_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id bigint NOT NULL REFERENCES public.arcusx_users (id) ON DELETE CASCADE,
  action text NOT NULL,
  target_type text,
  target_id bigint,
  details jsonb,
  ip_address text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_arcusx_admin_logs_admin ON public.arcusx_admin_logs (admin_id);
CREATE INDEX IF NOT EXISTS idx_arcusx_admin_logs_created ON public.arcusx_admin_logs (created_at DESC);

-- ---------------------------------------------------------------------------
-- Task progress
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.arcusx_task_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES public.arcusx_tasks (id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES public.arcusx_users (id) ON DELETE CASCADE,
  progress_type text NOT NULL CHECK (
    progress_type IN (
      'started', 'delivery', 'message', 'milestone',
      'cancellation_requested', 'cancellation_approved', 'cancellation_rejected'
    )
  ),
  description text,
  files jsonb,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_arcusx_task_progress_task ON public.arcusx_task_progress (task_id);

-- ---------------------------------------------------------------------------
-- User portfolio / skills / statistics
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.arcusx_user_portfolio (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.arcusx_users (id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  image_url text,
  project_url text,
  category text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.arcusx_user_skills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.arcusx_users (id) ON DELETE CASCADE,
  skill_name text NOT NULL,
  skill_level text NOT NULL DEFAULT 'intermediate'
    CHECK (skill_level IN ('beginner', 'intermediate', 'advanced', 'expert')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT arcusx_user_skills_unique UNIQUE (user_id, skill_name)
);

CREATE TABLE IF NOT EXISTS public.arcusx_user_statistics (
  user_id bigint PRIMARY KEY REFERENCES public.arcusx_users (id) ON DELETE CASCADE,
  tasks_completed integer NOT NULL DEFAULT 0,
  tasks_created integer NOT NULL DEFAULT 0,
  total_earned numeric(18, 8) NOT NULL DEFAULT 0,
  total_spent numeric(18, 8) NOT NULL DEFAULT 0,
  average_rating numeric(3, 2) NOT NULL DEFAULT 0,
  total_ratings integer NOT NULL DEFAULT 0,
  completion_rate numeric(5, 2) NOT NULL DEFAULT 0,
  response_time_avg text,
  last_calculated_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- RLS: deny direct client access (same pattern as messaging tables)
-- ---------------------------------------------------------------------------
ALTER TABLE public.arcusx_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arcusx_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arcusx_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arcusx_disputes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arcusx_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arcusx_system_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arcusx_admin_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arcusx_task_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arcusx_user_portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arcusx_user_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arcusx_user_statistics ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.arcusx_users FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.arcusx_tasks FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.arcusx_applications FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.arcusx_disputes FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.arcusx_ratings FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.arcusx_system_config FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.arcusx_admin_logs FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.arcusx_task_progress FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.arcusx_user_portfolio FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.arcusx_user_skills FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.arcusx_user_statistics FROM PUBLIC, anon, authenticated;

GRANT ALL ON TABLE public.arcusx_users TO postgres, service_role;
GRANT ALL ON TABLE public.arcusx_tasks TO postgres, service_role;
GRANT ALL ON TABLE public.arcusx_applications TO postgres, service_role;
GRANT ALL ON TABLE public.arcusx_disputes TO postgres, service_role;
GRANT ALL ON TABLE public.arcusx_ratings TO postgres, service_role;
GRANT ALL ON TABLE public.arcusx_system_config TO postgres, service_role;
GRANT ALL ON TABLE public.arcusx_admin_logs TO postgres, service_role;
GRANT ALL ON TABLE public.arcusx_task_progress TO postgres, service_role;
GRANT ALL ON TABLE public.arcusx_user_portfolio TO postgres, service_role;
GRANT ALL ON TABLE public.arcusx_user_skills TO postgres, service_role;
GRANT ALL ON TABLE public.arcusx_user_statistics TO postgres, service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

COMMENT ON TABLE public.arcusx_users IS 'Core users migrated from MySQL; operational access via service_role / Edge Functions only.';
