-- Backend completion: Realtime, escrow sync log, domain events, idempotency

-- ─── Realtime (notificaciones + mensajes) ───────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'arcusx_notifications'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.arcusx_notifications;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'arcusx_task_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.arcusx_task_messages;
  END IF;
EXCEPTION
  WHEN undefined_object THEN
    NULL; -- publication may not exist in local CLI
END $$;

-- ─── Escrow reconcile log ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.arcusx_escrow_sync_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint REFERENCES public.arcusx_tasks (id) ON DELETE SET NULL,
  agreement_id uuid REFERENCES public.arcusx_agreements (id) ON DELETE SET NULL,
  contract_id text NOT NULL,
  previous_status text,
  new_status text,
  source text NOT NULL DEFAULT 'reconcile',
  tx_hash text,
  payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_escrow_sync_log_task ON public.arcusx_escrow_sync_log (task_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_escrow_sync_log_contract ON public.arcusx_escrow_sync_log (contract_id);

ALTER TABLE public.arcusx_escrow_sync_log ENABLE ROW LEVEL SECURITY;

-- ─── Domain events (trazabilidad) ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.arcusx_domain_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  event_type text NOT NULL,
  actor_user_id bigint REFERENCES public.arcusx_users (id) ON DELETE SET NULL,
  payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_domain_events_entity
  ON public.arcusx_domain_events (entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_domain_events_type
  ON public.arcusx_domain_events (event_type, created_at DESC);

ALTER TABLE public.arcusx_domain_events ENABLE ROW LEVEL SECURITY;

-- ─── Idempotencia API (POST críticos) ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.arcusx_idempotency_keys (
  idempotency_key text PRIMARY KEY,
  action text NOT NULL,
  user_id bigint,
  response_status int NOT NULL,
  response_body jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_idempotency_created ON public.arcusx_idempotency_keys (created_at);

ALTER TABLE public.arcusx_idempotency_keys ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.arcusx_domain_events IS 'Auditoría operativa: tareas, escrow, deals, disputas';
COMMENT ON TABLE public.arcusx_escrow_sync_log IS 'Log de reconciliación escrow (cron Edge)';
COMMENT ON TABLE public.arcusx_idempotency_keys IS 'Respuestas cacheadas 24h para POST idempotentes';
