-- Email transaccional: cola outbox + preferencia por usuario

ALTER TABLE public.arcusx_users
  ADD COLUMN IF NOT EXISTS email_notifications_enabled boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS public.arcusx_email_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id_mysql bigint REFERENCES public.arcusx_users (id) ON DELETE SET NULL,
  to_email text NOT NULL,
  subject text NOT NULL,
  body_text text NOT NULL,
  body_html text,
  template_key text,
  notification_id bigint,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
  error_message text,
  attempts int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  sent_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_arcusx_email_outbox_pending
  ON public.arcusx_email_outbox (created_at)
  WHERE status = 'pending';

ALTER TABLE public.arcusx_email_outbox ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.arcusx_email_outbox IS 'Cola SMTP; procesada por Edge arcusx-email-worker';
