-- ArcusX Deals: acuerdos P2P con link de pago y escrow USDC.
-- Acceso vía Edge Functions (service_role); RLS sin políticas para anon/auth.

CREATE TABLE IF NOT EXISTS public.arcusx_agreements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  deal_token text NOT NULL,
  template_id text NOT NULL DEFAULT 'other',
  payment_mode text NOT NULL DEFAULT 'one_time' CHECK (payment_mode IN ('one_time', 'milestone')),
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  initiator_user_id bigint NOT NULL REFERENCES public.arcusx_users (id) ON DELETE CASCADE,
  counterparty_user_id bigint REFERENCES public.arcusx_users (id) ON DELETE SET NULL,
  initiator_wallet text NOT NULL,
  counterparty_wallet text,
  release_signer_wallet text NOT NULL,
  beneficiary_wallet text NOT NULL,
  funder_role text NOT NULL DEFAULT 'counterparty' CHECK (funder_role IN ('initiator', 'counterparty')),
  amount_usdc numeric(18, 8) NOT NULL,
  fee_usdc numeric(18, 8) NOT NULL DEFAULT 0,
  client_total numeric(18, 8) NOT NULL,
  platform_fee_rate numeric(10, 7),
  status text NOT NULL DEFAULT 'sent' CHECK (
    status IN (
      'draft', 'sent', 'accepted', 'funding', 'funded', 'active',
      'completed', 'cancelled', 'disputed'
    )
  ),
  escrow_contract_id text,
  escrow_tx_hash text,
  legacy_task_id bigint REFERENCES public.arcusx_tasks (id) ON DELETE SET NULL,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  funded_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT arcusx_agreements_deal_token_unique UNIQUE (deal_token)
);

CREATE INDEX IF NOT EXISTS idx_arcusx_agreements_token ON public.arcusx_agreements (deal_token);
CREATE INDEX IF NOT EXISTS idx_arcusx_agreements_initiator ON public.arcusx_agreements (initiator_user_id);
CREATE INDEX IF NOT EXISTS idx_arcusx_agreements_counterparty ON public.arcusx_agreements (counterparty_user_id);
CREATE INDEX IF NOT EXISTS idx_arcusx_agreements_status ON public.arcusx_agreements (status);

CREATE TABLE IF NOT EXISTS public.arcusx_agreement_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_id uuid NOT NULL REFERENCES public.arcusx_agreements (id) ON DELETE CASCADE,
  event_type text NOT NULL,
  actor_user_id bigint REFERENCES public.arcusx_users (id) ON DELETE SET NULL,
  payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_arcusx_agreement_events_agreement
  ON public.arcusx_agreement_events (agreement_id, created_at DESC);

ALTER TABLE public.arcusx_agreements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arcusx_agreement_events ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.arcusx_agreements IS 'Deals P2P: link de pago + escrow hasta liberación condicional';
