-- Disputas y evidencia para deals (arcusx_agreements)

ALTER TABLE public.arcusx_disputes
  ALTER COLUMN task_id DROP NOT NULL;

ALTER TABLE public.arcusx_disputes
  ADD COLUMN IF NOT EXISTS agreement_id uuid REFERENCES public.arcusx_agreements (id) ON DELETE CASCADE;

ALTER TABLE public.arcusx_disputes
  DROP CONSTRAINT IF EXISTS arcusx_disputes_entity_chk;

ALTER TABLE public.arcusx_disputes
  ADD CONSTRAINT arcusx_disputes_entity_chk CHECK (
    (task_id IS NOT NULL AND agreement_id IS NULL)
    OR (task_id IS NULL AND agreement_id IS NOT NULL)
  );

CREATE INDEX IF NOT EXISTS idx_arcusx_disputes_agreement
  ON public.arcusx_disputes (agreement_id)
  WHERE agreement_id IS NOT NULL;

ALTER TABLE public.arcusx_agreements
  ADD COLUMN IF NOT EXISTS escrow_status text;

COMMENT ON COLUMN public.arcusx_agreements.escrow_status IS
  'Paridad con tasks: disputed, pending_dispute_resolution, resolved, refunded';

CREATE TABLE IF NOT EXISTS public.arcusx_deal_evidence (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_id uuid NOT NULL REFERENCES public.arcusx_agreements (id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES public.arcusx_users (id) ON DELETE CASCADE,
  note text,
  files jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_deal_evidence_agreement
  ON public.arcusx_deal_evidence (agreement_id, created_at DESC);

ALTER TABLE public.arcusx_deal_evidence ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.arcusx_deal_evidence IS
  'Evidencia subida por iniciador o contraparte en el espacio del deal (para disputas admin).';
