import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'
import { VitePWA } from 'vite-plugin-pwa'
import { copyFileSync, existsSync, writeFileSync, readFileSync } from 'fs'
import { join } from 'path'
import { createRequire } from 'module'

const require = createRequire(import.meta.url)

// Importar purgecss solo en build
let purgecssPlugin: any = null;
if (process.env.NODE_ENV === 'production') {
  try {
    const purgecssModule = require('@fullhuman/postcss-purgecss');
    // El módulo exporta default (función) o purgeCSSPlugin
    purgecssPlugin = purgecssModule.default || purgecssModule.purgeCSSPlugin;
  } catch (e) {
    console.warn('PurgeCSS no disponible:', e);
  }
}

// Plugin para copiar .htaccess al build y agregar banners a archivos JS
// NOTA: El .htaccess consolidado está en backend_externo/ y debe moverse manualmente a public_html/
const copyHtaccess = () => {
  // Banner simple para archivos JS
  const jsBanner = `/*!
 * ArcusX Platform - Generated by Vite.js
 * https://arcusx.pro
 */
`
  
  // Función para agregar banner a todos los archivos JS en dist/
  const addBannersToJSFiles = () => {
    try {
      const { readdirSync, readFileSync, writeFileSync, statSync } = require('fs')
      const { join } = require('path')
      
      const distPath = join(__dirname, 'dist')
      const assetsPath = join(distPath, 'assets')
      
      // Función recursiva para procesar archivos
      const processDirectory = (dir: string) => {
        try {
          const files = readdirSync(dir)
          files.forEach((file: string) => {
            const filePath = join(dir, file)
            const stat = statSync(filePath)
            
            if (stat.isDirectory()) {
              processDirectory(filePath)
            } else if (file.endsWith('.js') && !file.includes('workbox')) {
              try {
                const content = readFileSync(filePath, 'utf-8')
                // Solo agregar banner si no existe ya
                if (!content.includes('ArcusX Platform')) {
                  writeFileSync(filePath, jsBanner + content, 'utf-8')
                }
              } catch (error: any) {
                // Ignorar errores de archivos individuales
              }
            }
          })
        } catch (error: any) {
          // Ignorar errores de directorios
        }
      }
      
      // Procesar assets y dist directamente
      if (existsSync(assetsPath)) {
        processDirectory(assetsPath)
      }
      processDirectory(distPath)
      
      console.log('✅ Banners agregados a archivos JavaScript para evitar falsos positivos')
    } catch (error: any) {
      console.warn('⚠️ No se pudieron agregar banners a todos los JS:', error.message)
    }
  }
  
  // Función para procesar Service Worker
  const processFiles = () => {
    try {
      // Agregar banner extenso al Service Worker para evitar falsos positivos de antivirus
      // Intentar múltiples veces porque el SW se genera de forma asíncrona
      const swPath = join(__dirname, 'dist', 'sw.js')
      const banner = `/*!
 * ============================================================================
 * Service Worker - ArcusX Platform
 * ============================================================================
 * 
 * ARCHIVO LEGÍTIMO GENERADO AUTOMÁTICAMENTE
 * Este archivo es parte de una Progressive Web App (PWA) y es necesario
 * para el funcionamiento offline y el cacheo de recursos.
 * 
 * NO CONTIENE CÓDIGO MALICIOSO
 * Este Service Worker es generado por vite-plugin-pwa, un plugin oficial
 * y ampliamente utilizado para Vite.js.
 * 
 * Propósito:
 * - Cachear recursos estáticos para mejor rendimiento
 * - Permitir funcionamiento offline básico
 * - Gestionar actualizaciones de la aplicación
 * 
 * Información técnica:
 * - Generado por: vite-plugin-pwa v1.2.0
 * - Framework: Vite.js + React
 * - Fecha de generación: ${new Date().toISOString()}
 * - Proyecto: ArcusX - Plataforma de Freelancing Web3
 * 
 * Documentación oficial:
 * https://vite-pwa-org.netlify.app/
 * https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
 * 
 * Si este archivo es detectado como falso positivo, por favor reporta
 * el problema al proveedor de tu antivirus con esta información.
 * ============================================================================
 */

`
      
      let attempts = 0
      const maxAttempts = 10
      const tryAddBanner = () => {
        attempts++
        if (existsSync(swPath)) {
          try {
            const swContent = readFileSync(swPath, 'utf-8')
            // Solo agregar el banner si no existe ya
            if (!swContent.includes('ARCHIVO LEGÍTIMO GENERADO AUTOMÁTICAMENTE')) {
              writeFileSync(swPath, banner + swContent, 'utf-8')
              console.log('✅ Banner extenso agregado al Service Worker para evitar falsos positivos')
            }
          } catch (error: any) {
            console.error('❌ Error al agregar banner al SW:', error.message)
          }
        } else if (attempts < maxAttempts) {
          // Reintentar después de 200ms
          setTimeout(tryAddBanner, 200)
        }
      }
      
      // Iniciar intentos
      tryAddBanner()
    } catch (error: any) {
      console.error('❌ Error al procesar archivos:', error.message)
    }
  }

  return {
    name: 'copy-htaccess',
    closeBundle() {
      // Procesar .htaccess inmediatamente
      try {
        const backendHtaccess = join(__dirname, '..', 'backend_externo', '.htaccess')
        const dest = join(__dirname, 'dist', '.htaccess')
        
        if (existsSync(backendHtaccess)) {
          copyFileSync(backendHtaccess, dest)
          console.log('✅ .htaccess copiado desde backend_externo/ a dist/')
        } else {
          const htaccessContent = `DirectoryIndex index.html

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteCond %{REQUEST_URI} !^/api/
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>`
          writeFileSync(dest, htaccessContent)
          console.log('✅ .htaccess básico creado en dist/')
        }
      } catch (error: any) {
        console.error('❌ Error al copiar .htaccess:', error.message)
      }
      
      // Agregar banners a todos los archivos JS después del build
      // Esperar un poco para que Vite termine de generar todos los archivos
      setTimeout(() => {
        addBannersToJSFiles();
        
        // Procesar Service Worker solo si PWA está habilitado
        if (process.env.ENABLE_PWA === 'true') {
          setTimeout(() => {
            processFiles();
          }, 1000);
        }
      }, 3000);
    }
  }
}

// https://vite.dev/config/
export default defineConfig({
  // Cargar .env siempre desde esta carpeta (arcusx), aunque el build se ejecute desde otra ruta
  envDir: join(__dirname),
  plugins: [
    react(), 
    copyHtaccess(),
    // PWA deshabilitado por defecto para evitar falsos positivos de antivirus en cPanel
    // Para habilitar: ENABLE_PWA=true npm run build
    ...(process.env.ENABLE_PWA === 'true' ? [VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.ico', 'logo192.png', 'logo512.png'],
      manifest: {
        name: 'ArcusX - Plataforma de Freelancing Web3',
        short_name: 'ArcusX',
        description: 'Plataforma descentralizada de freelancing con pagos en USDC sobre Stellar',
        theme_color: '#28c0f0',
        background_color: '#07233c',
        display: 'standalone',
        orientation: 'portrait-primary',
        scope: '/',
        start_url: '/',
        icons: [
          {
            src: '/logo192.png',
            sizes: '192x192',
            type: 'image/png'
          },
          {
            src: '/logo512.png',
            sizes: '512x512',
            type: 'image/png'
          }
        ]
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,ico,png,svg,webp,woff,woff2}'],
        maximumFileSizeToCacheInBytes: 3 * 1024 * 1024, // 3 MB
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/arcusx\.pro\/api\/.*/i,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'api-cache',
              expiration: {
                maxEntries: 50,
                maxAgeSeconds: 60 * 60 // 1 hora
              },
              cacheableResponse: {
                statuses: [0, 200]
              }
            }
          },
          {
            urlPattern: /^https:\/\/.*\.(?:png|jpg|jpeg|svg|gif|webp)$/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'images-cache',
              expiration: {
                maxEntries: 100,
                maxAgeSeconds: 60 * 60 * 24 * 30 // 30 días
              }
            }
          }
        ]
      },
      devOptions: {
        enabled: false // Deshabilitar en desarrollo para evitar problemas
      }
    })] : [])
  ],
  define: {
    global: 'globalThis',
    'process.env': {},
  },
  optimizeDeps: {
    include: ['@creit.tech/stellar-wallets-kit'],
    esbuildOptions: {
      define: {
        global: 'globalThis',
      },
    },
  },
  css: {
    postcss: {
      plugins: [
        ...(purgecssPlugin ? [purgecssPlugin({
          content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
          safelist: [
            // Página /empresas (prefijo ax-empresas__)
            /^ax-empresas/,
            /^empresas-navbar/,
            'login-container--enterprise',
            'register-container--enterprise',
            'dashboard--enterprise',
            // Clases de tema
            'dark',
            'light',
            /^data-theme/,
            // Clases dinámicas comunes
            /^theme-/,
            /^mode-/,
            // Clases de Chakra UI
            /^chakra-/,
            /^css-/,
            // Clases que pueden generarse dinámicamente
            /^loading/,
            /^error/,
            /^success/,
            // Botón de idioma (LanguageFab) - evita que PurgeCSS lo elimine en producción
            /^lang-select/,
            'lang-select',
            'lang-select--fab',
            'lang-select--inline',
            'lang-select-trigger',
            'lang-select-dropdown',
            'lang-select-option',
            'lang-select-icon',
            'lang-select-label',
            'lang-select-chevron',
            'theme-language-buttons',
            // Mantener todas las clases que contengan estas palabras clave
            /active/,
            /hover/,
            /focus/,
            /disabled/,
            /selected/,
            /open/,
            /closed/
          ],
          defaultExtractor: (content: string) => {
            // Extraer clases de manera más agresiva
            const broadMatches = content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || [];
            const innerMatches = content.match(/[^<>"'`\s.()]*[^<>"'`\s.():]/g) || [];
            return [...broadMatches, ...innerMatches];
          }
        })] : [])
      ]
    }
  },
  build: {
    commonjsOptions: {
      include: [/node_modules/]
    },
    rollupOptions: {
      onwarn(warning: any, warn: any) {
        // Suprimir warnings de buffer y otros módulos Node.js externalizados
        if (warning.code === 'MODULE_LEVEL_DIRECTIVE' || 
            warning.message?.includes('externalized for browser compatibility')) {
          return;
        }
        warn(warning);
      },
    },
  },
  server: {
    fs: {
      allow: ['..']
    }
  }
})
